plugins {
    id 'com.android.application'
}

android {
    namespace 'com.github.barteksc.sample'
    compileSdk 35

    defaultConfig {
        applicationId 'gr.kingpool.headsetdiag.v2'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '1.3-z3'
    }

    sourceSets {
        main {
            java.srcDirs = ['src/diagnostic/java']
            res.srcDirs = []
            assets.srcDirs = []
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
